#FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Install the xz-utils package
#RUN apt-get update && apt-get install -y python3.6 python3-pip

FROM python:3.6
#3.7
#FROM ubuntu:19.10
#:18.04

# Set the locale to C.UTF-8
#ENV LANG=C.UTF-8
#ENV LC_ALL=C.UTF-8

ENV PYTHONPATH="/workspaces/EmoPy"

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y libgl1-mesa-glx
RUN pip install --upgrade pip

#RUN pip install -r requirements-working.txt



#RUN apt-get update
#RUN apt-get install -y python3.7
#RUN apt-get install -y python3-pip
#RUN apt-get install -y python3-venv
#RUN python3.7 -m pip install virtualenv
#RUN python3.7 -m pip install scikit-build

# 

# This will install Python, pip, pip3, and pip3.6.

#RUN curl https://bootstrap.pypa.io/ez_setup.py -o - | python3.6 && python3.6 -m easy_install pip
#RUN python3.6 && python3.6 -m easy_install pip
#RUN apt-get update
#RUN apt-get install -y python3.6-venv

# Inorder to run pip3.6, run it the following way `python3.6 -m pip`
# Update Python & Install wheel
#RUN python3.6 -m pip install pip --upgrade
#RUN python3.6 -m pip install wheel



