# DOCKERFILE to build environment for EmoPy
FROM python:3.6

ENV PYTHONPATH="/workspaces/EmoPy"

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y libgl1-mesa-glx
RUN pip install --upgrade pip
